[alias]
coverage_clean = ["llvm-cov", "clean", "--workspace"]
coverage_0 = ["llvm-cov", "--no-report", "nextest"]
coverage_1 = ["llvm-cov", "--no-report", "nextest", "--all-features"]
coverage_merge = 'llvm-cov report --lcov --output-path ./target/coverage/lcov.info'
coverage_open = 'llvm-cov report --open --output-dir ./target/coverage'
